// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfilSena.API.Data;

#nullable disable

namespace PerfilSena.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerfilSena.API.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PabloReyesEmisorId")
                        .HasColumnType("int");

                    b.Property<int>("PabloReyesReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PabloReyesReceptorId");

                    b.HasIndex("PabloReyesEmisorId", "PabloReyesReceptorId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("PerfilSena.API.Models.PabloReyes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("PabloReyes");
                });

            modelBuilder.Entity("PerfilSena.API.Models.Comentario", b =>
                {
                    b.HasOne("PerfilSena.API.Models.PabloReyes", "PabloReyesEmisor")
                        .WithMany("ComentariosEnviados")
                        .HasForeignKey("PabloReyesEmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerfilSena.API.Models.PabloReyes", "PabloReyesReceptor")
                        .WithMany("ComentariosRecibidos")
                        .HasForeignKey("PabloReyesReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PabloReyesEmisor");

                    b.Navigation("PabloReyesReceptor");
                });

            modelBuilder.Entity("PerfilSena.API.Models.PabloReyes", b =>
                {
                    b.Navigation("ComentariosEnviados");

                    b.Navigation("ComentariosRecibidos");
                });
#pragma warning restore 612, 618
        }
    }
}
